### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sikron** [loia/springmvc-wadlgen#1]
Hi Alan,
i found this neat little project of yours and want to use it in a project at my work here. Unfortunately you do not have specified the license of your code. It would be really great, if you could do that. If possible i would prefer MIT as it is non-viral and would cause the least issues here at my work.

Thank very much! I am looking forward to hear from you again!

bye
Simon

**Comment by loia** [comment]
Hi Simon,

No problem - I've added an Apache 2.0 license.  Hope that works for you.

Cheers,
Alan

**Comment by sikron** [comment]
Hi Alan,
thank you for the quick response and the license! 
Apache 2 is fine for me.

bye
Simon
